# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PrePush < Formula
  desc "Cross-platform Git pre-push hook runner with DAG-based execution"
  homepage "https://github.com/AlexBurnes/pre-push"
  version "1.1.0"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/AlexBurnes/pre-push/releases/download/v1.1.0/pre-push_macos_amd64.tar.gz"
      sha256 "c935f298c15271a407bdece63a520ea71a56d78cdb3bd2098f9ae64609f0927f"

      def install
        bin.install "pre-push"
      end
    end
    on_arm do
      url "https://github.com/AlexBurnes/pre-push/releases/download/v1.1.0/pre-push_macos_arm64.tar.gz"
      sha256 "3d248ddac31ea5b4de2a06ec51dc4356a22186346842dd64b9edbabda376c1d5"

      def install
        bin.install "pre-push"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/AlexBurnes/pre-push/releases/download/v1.1.0/pre-push_linux_amd64.tar.gz"
        sha256 "4c71adf14d01399a9bbac7deb53db496c250150e918a9b571948eea0fdb63987"

        def install
          bin.install "pre-push"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/AlexBurnes/pre-push/releases/download/v1.1.0/pre-push_linux_arm64.tar.gz"
        sha256 "d80441e8f171c24051dd748eb3cf8634bcf8a6b2a1275e03917a7aa4d7dbf625"

        def install
          bin.install "pre-push"
        end
      end
    end
  end

  test do
    system "#{bin}/pre-push --version"
    system "#{bin}/pre-push --help"
    system "#{bin}/pre-push list-uses"
  end
end
