# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PrePush < Formula
  desc "Cross-platform Git pre-push hook runner with DAG-based execution"
  homepage "https://github.com/AlexBurnes/pre-push"
  version "1.6.9"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/AlexBurnes/pre-push/releases/download/v1.6.9/pre-push_darwin_amd64.tar.gz"
      sha256 "f3f089fb38413c0673ce40b1cde4860167fe6ddc37334c95a918caca96984c89"

      def install
        bin.install "pre-push"
      end
    end
    on_arm do
      url "https://github.com/AlexBurnes/pre-push/releases/download/v1.6.9/pre-push_darwin_arm64.tar.gz"
      sha256 "1cd0b70beb92814ab4b426aebe7c476fddc92fd7c716cd3f250ff6ad35a923e1"

      def install
        bin.install "pre-push"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/AlexBurnes/pre-push/releases/download/v1.6.9/pre-push_linux_amd64.tar.gz"
        sha256 "5730e983831434c37502c7fb6151fce9a4b90e4eca68ead4ff420df9697292fb"

        def install
          bin.install "pre-push"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/AlexBurnes/pre-push/releases/download/v1.6.9/pre-push_linux_arm64.tar.gz"
        sha256 "506987aa402262d9afad1f30f7fbd79a640abef02ec726802d418d275c8e88bb"

        def install
          bin.install "pre-push"
        end
      end
    end
  end

  test do
    system "#{bin}/pre-push --version"
    system "#{bin}/pre-push --help"
    system "#{bin}/pre-push list-uses"
  end
end
