# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PrePush < Formula
  desc "Cross-platform Git pre-push hook runner with DAG-based execution"
  homepage "https://github.com/AlexBurnes/pre-push"
  version "1.10.1"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/AlexBurnes/pre-push/releases/download/v1.10.1/pre-push_darwin_amd64.tar.gz"
      sha256 "de926ef164201282baae62b9191e4463a7fdbb8724de4c9b20587c482ae6808c"

      def install
        bin.install "pre-push"
      end
    end
    on_arm do
      url "https://github.com/AlexBurnes/pre-push/releases/download/v1.10.1/pre-push_darwin_arm64.tar.gz"
      sha256 "d0f148ec5016659c9a534a20819286401a62678086d74b7b20dffbbc2321934d"

      def install
        bin.install "pre-push"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/AlexBurnes/pre-push/releases/download/v1.10.1/pre-push_linux_amd64.tar.gz"
        sha256 "135d079b0d0baaaa2e983bdd64785ec9f483fc241ba78c0bdaae408936c80946"

        def install
          bin.install "pre-push"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/AlexBurnes/pre-push/releases/download/v1.10.1/pre-push_linux_arm64.tar.gz"
        sha256 "82af2a8dd4c196271dd6fe36972dac24003f14ebd573938324087670f7903cc2"

        def install
          bin.install "pre-push"
        end
      end
    end
  end

  test do
    system "#{bin}/pre-push --version"
    system "#{bin}/pre-push --help"
    system "#{bin}/pre-push list-uses"
  end
end
