# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Version < Formula
  desc "Cross-platform semantic version parsing, validation, and ordering CLI utility"
  homepage "https://github.com/AlexBurnes/version-go"
  version "1.1.1"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/AlexBurnes/version-go/releases/download/v1.1.1/version_macos_amd64.tar.gz"
      sha256 "e1a7d37243148ca3a6cf3c8e42ca1e579e52e01a2c3ed5e892fc8968563a610d"

      def install
        bin.install "version"
      end
    end
    on_arm do
      url "https://github.com/AlexBurnes/version-go/releases/download/v1.1.1/version_macos_arm64.tar.gz"
      sha256 "94b54be08d316a41a19afc2ce1c230d10b5dfb26663247303a8b594ad0a94d28"

      def install
        bin.install "version"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/AlexBurnes/version-go/releases/download/v1.1.1/version_linux_amd64.tar.gz"
        sha256 "51980b7de19210426d99f43c9069a434f34e1ad0d944bfaa61bc82fde69c92c3"

        def install
          bin.install "version"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/AlexBurnes/version-go/releases/download/v1.1.1/version_linux_arm64.tar.gz"
        sha256 "854e265620e102ebcdd2fcd1cd6f09fd14ede4da16d81b1ab080216759386f30"

        def install
          bin.install "version"
        end
      end
    end
  end

  test do
    system "#{bin}/version --version"
    system "#{bin}/version type 1.2.3"
    system "#{bin}/version type 1.2.3~alpha.1"
    system "#{bin}/version type 1.2.3.fix.1"
    system "#{bin}/version type 1.2.3_feature_1"
  end
end
