# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Version < Formula
  desc "Cross-platform semantic version parsing, validation, and ordering CLI utility"
  homepage "https://github.com/AlexBurnes/version-go"
  version "1.1.0"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/AlexBurnes/version-go/releases/download/v1.1.0/version_macos_amd64.tar.gz"
      sha256 "9d31b0ea6c52ae569d1ace22f11eecd0ce346a00090f596df956726bf0bc425c"

      def install
        bin.install "version"
      end
    end
    on_arm do
      url "https://github.com/AlexBurnes/version-go/releases/download/v1.1.0/version_macos_arm64.tar.gz"
      sha256 "43e998eca76bfa85c6887a32385a98b4e08e2fa53a0780cc85382ced6f9b622c"

      def install
        bin.install "version"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/AlexBurnes/version-go/releases/download/v1.1.0/version_linux_amd64.tar.gz"
        sha256 "471a0f9820745de52632ad1e6487fbc94c35b34661cdd70b203b8687c3a6767f"

        def install
          bin.install "version"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/AlexBurnes/version-go/releases/download/v1.1.0/version_linux_arm64.tar.gz"
        sha256 "d305c94e3905b3ecfd60a1a92e755010aecd3032ac1ff79e8caa9288cb9ac906"

        def install
          bin.install "version"
        end
      end
    end
  end

  test do
    system "#{bin}/version --version"
    system "#{bin}/version type 1.2.3"
    system "#{bin}/version type 1.2.3~alpha.1"
    system "#{bin}/version type 1.2.3.fix.1"
    system "#{bin}/version type 1.2.3_feature_1"
  end
end
