# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Version < Formula
  desc "Cross-platform semantic version parsing, validation, and ordering CLI utility"
  homepage "https://github.com/AlexBurnes/version-go"
  version "0.8.2"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/AlexBurnes/version-go/releases/download/v0.8.2/version_0.8.2_darwin_amd64.tar.gz"
      sha256 "53ebaf59a5d12d4b44779a2e2c03db153026fd0bf321e4120cc76e608ec523a5"

      def install
        bin.install "version"
      end
    end
    on_arm do
      url "https://github.com/AlexBurnes/version-go/releases/download/v0.8.2/version_0.8.2_darwin_arm64.tar.gz"
      sha256 "6bbc3a5c4638382d98685800fb3df94ccfe89967ac9e233ac16614b9e5a9bdfd"

      def install
        bin.install "version"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/AlexBurnes/version-go/releases/download/v0.8.2/version_0.8.2_linux_amd64.tar.gz"
        sha256 "32d5755548c18ce3aca54dc423278d6b3bbbbadd1886bb7dc0a17a632ebc73aa"

        def install
          bin.install "version"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/AlexBurnes/version-go/releases/download/v0.8.2/version_0.8.2_linux_arm64.tar.gz"
        sha256 "e3b860a61e1e3dccfb47df8d9ecff2be59c87b0db78bea73a0e0db6d554e9cb8"

        def install
          bin.install "version"
        end
      end
    end
  end

  test do
    system "#{bin}/version --version"
    system "#{bin}/version type 1.2.3"
    system "#{bin}/version type 1.2.3~alpha.1"
    system "#{bin}/version type 1.2.3.fix.1"
    system "#{bin}/version type 1.2.3_feature_1"
  end
end
