# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Version < Formula
  desc "Cross-platform semantic version parsing, validation, and ordering CLI utility"
  homepage "https://github.com/AlexBurnes/version-go"
  version "1.2.6"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/AlexBurnes/version-go/releases/download/v1.2.6/version_darwin_amd64.tar.gz"
      sha256 "abae5ef065f781c410095ad226f7e05ac5d3d4014effbd84bf0928694ed7e99b"

      def install
        bin.install "version"
      end
    end
    on_arm do
      url "https://github.com/AlexBurnes/version-go/releases/download/v1.2.6/version_darwin_arm64.tar.gz"
      sha256 "c2a28c61c4e1a5d5a9f2799148839b4fa7df0e8e24ce835b77d10f8f75cd1679"

      def install
        bin.install "version"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/AlexBurnes/version-go/releases/download/v1.2.6/version_linux_amd64.tar.gz"
        sha256 "216ae49e0f07544b35dffd5f849664c9138be05aa9ffe87e1309986fe952ecc5"

        def install
          bin.install "version"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/AlexBurnes/version-go/releases/download/v1.2.6/version_linux_arm64.tar.gz"
        sha256 "8e4862d290ac4df38465b707d38d369f65bce1ae170bd08eb7719e0389b25c36"

        def install
          bin.install "version"
        end
      end
    end
  end

  test do
    system "#{bin}/version --version"
    system "#{bin}/version type 1.2.3"
    system "#{bin}/version type 1.2.3~alpha.1"
    system "#{bin}/version type 1.2.3.fix.1"
    system "#{bin}/version type 1.2.3_feature_1"
  end
end
