# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Version < Formula
  desc "Cross-platform semantic version parsing, validation, and ordering CLI utility"
  homepage "https://github.com/AlexBurnes/version-go"
  version "1.6.1"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/AlexBurnes/version-go/releases/download/v1.6.1/version_darwin_amd64.tar.gz"
      sha256 "905ba7b60577edf5cc9de02e1e1b91d35a34e869492de462196aba94ee2e8abe"

      def install
        bin.install "version"
      end
    end
    on_arm do
      url "https://github.com/AlexBurnes/version-go/releases/download/v1.6.1/version_darwin_arm64.tar.gz"
      sha256 "36d006a7124544a0658ae162c5a561df96e034dc1d55f45c2c5b610efd8080df"

      def install
        bin.install "version"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/AlexBurnes/version-go/releases/download/v1.6.1/version_linux_amd64.tar.gz"
        sha256 "82d924249f0e3da7acba6f293121fc8d4c771a6140f8901addee1298549b8239"

        def install
          bin.install "version"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/AlexBurnes/version-go/releases/download/v1.6.1/version_linux_arm64.tar.gz"
        sha256 "5bca6a46b59ac0bf803e28ff06c8a6711204a17567462f59b2f42d31a84acc8e"

        def install
          bin.install "version"
        end
      end
    end
  end

  test do
    system "#{bin}/version --version"
    system "#{bin}/version type 1.2.3"
    system "#{bin}/version type 1.2.3~alpha.1"
    system "#{bin}/version type 1.2.3.fix.1"
    system "#{bin}/version type 1.2.3_feature_1"
  end
end
